version: "3.4"
services:
  aero:
    build:
      context: .
      network: host
    image: blitzprog/aero
    network_mode: host
    stdin_open: true
    tty: true
    volumes:
      - ~:/home/developer/host